### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by magnetophon** [rabite0/hunter#76]
While testing some more scrolling, I got a crash, with this output:
```
thread '<unnamed>' panicked at 'byte index 61 is not a char boundary; it is inside 'ʻ' (bytes 60..62) of `OFFICIAL Somewhere over the Rainbow - Israel 'IZ' Kamakawiwoʻole-V1bFr2SWP1I.mkv`', src/libcore/str/mod.rs:2154:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by magnetophon** [comment]
with RUST_BACKTRACE=1
```
thread '<unnamed>' panicked at 'byte index 61 is not a char boundary; it is inside 'ʻ' (bytes 60..62) of `OFFICIAL Somewhere over the Rainbow - Israel 'IZ' Kamakawiwoʻole-V1bFr2SWP1I.mkv`', src/libcore/str/mod.rs:2154:5
stack backtrace:
j   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: hunter::die_gracefully::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
  12: rust_begin_unwind
             at src/libstd/panicking.rs:380
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::str::slice_error_fail
             at src/libcore/str/mod.rs:0
  15: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index::{{closure}}
             at src/libcore/str/mod.rs:1854
  16: hunter::term::sized_string
  17: hunter::listview::ListView<hunter::files::Files>::render_line_fn::{{closure}}
  18: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  19: hunter::listview::FileListBuilder::build
  20: hunter::preview::Previewer::set_file::{{closure}}
  21: core::ops::function::FnOnce::call_once{{vtable.shim}}
  22: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by rabite0** [comment]
Things are a bit crazy with all the optimization work going on right now.
This should be working now with the latest commit.

**Comment by magnetophon** [comment]
Yup, fixed!
